spring:
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  #  sql:
  #    init:
  #      mode: never
  #data.sql ?? X
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource: #?????? ?? ??
    url : jdbc:h2:mem:testDB2
    username : root
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    hikari:
      password: 1234

  h2: #H2 ?? ???
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
    # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)






